### ISSUE TITLE
What is the target output for our PDF?

### ISSUE THREAD

**Issue by Lokathor** [SqueeG/awesomeTome#13]
Are we aiming for phones/tablets, or PC screens, or some specific size of paper so that we could maybe have it printed in a shop, or what?

Basically, on a tablet or phone you want smaller pages and large text so that you can read it properly at all. However, that makes it hard to place tables and figures, and makes it look kinda dumb on a PC screen.

It's not at all trivial to just make both versions, because the pageflow is totally different when you change paper size. If you want tables and figures to be at all placed properly you need to move them around after you've got your text flow determined. So we should pick what we're making, and if we can later make a secondary version later then that'll be nice but not something to count on because it'll honestly be another pile of work on top of the large piles of work we've already arranged for ourselves.

**Comment by SqueeG** [comment]
US Letter sized paper. Considering a few people have mentioned printing pages off for their groups.... and most of us are US based.

My 2c.

**Comment by Tarkisflux** [comment]
I support 8.5" x 11", which should look like any other pdf copy of a book I have already if I wanted to put it up on a monitor, tablet, or phone.

**Comment by ExplosiveRunes** [comment]
I also support 8.5" x 11" Do we want single or double columns?

A note about the 'nice' version we might make. I did a little research, and its fairly easy to add background images to a PDF using PDF editing software, while its a straight up bitch to work with images in latex. If we we wanted, we could set up chapter starts and whatnot to simply leave a standardized area of blank space and add any art we wanted as a background. Same thing with fancy borders or column divisions or whatever. For example, if someone did a races lineup drawing, we could just format one of the pages in the races section to leave the top 1/3 of the page empty, and insert an background image that had that artwork in that area.  It wouldn't be perfect, and it would no longer be completely latex, but it seems like it would be _simple_.

**Comment by SqueeG** [comment]
I was just looking up adding background and border images last night. Using yhe wallpaper library doesnt look too bad.

**Comment by Tarkisflux** [comment]
I strongly prefer double columns, but that makes table placement a bit annoying I imagine.

**Comment by ghost** [comment]
Not really - LaTeX can handle it just fine. In fact, there's a whole major journal out there for computer science (STOC, to be exact) which _only_ accepts two-column entries, and it looks fine to me.

**Comment by ExplosiveRunes** [comment]
Eh, it _does_ make placing certain types of tables more of a hassle, but it can be done, usually by placing the table outside of the multicolumn format and having it appear at the top or the bottom of the page (an example of this being the contact other plane table in spells.tex which displays fine in conjunction with the two column environment, though it does need to be moved)

**Comment by Lokathor** [comment]
Two-column is a bitch to place tables and figures within. It just is. The only sane way to do it is to end the multi-column that you've got going, place the figure, and then start a new multi-column. This means that even for incidental tables you can't flow words around the table. Unless the table is SO small that it fits inside of a single column, in which case you can just put it in the column.

Single Column is far superior in terms of making tables and figures easy, and also if you have to zoom in because you're on a smaller device then you don't have to scroll down then back up over and over as you go from column A to column B on each page while reading. The downsides of Single Column are that you end up with more trailing whitespace if a paragraph ends early in a line, which can make the text seem slightly less compact overall. I don't think that's a huge deal though.

The only section of the book that I think we'd want to go with double column on would be the Spell Entries appendix.

**Comment by ghost** [comment]
Lokathor makes a valid point with respect to scrolling and reading in a two-column format. As someone who reads game books on a laptop, I can certainly see his point.

**Comment by Tarkisflux** [comment]
Closing with the following resolution:

Single column (except maybe spells), 8.5x11 inch paper. Tables remain annoying.
