### ISSUE TITLE
New feats file breaks legacysource

### ISSUE THREAD

**Issue by ExplosiveRunes** [SqueeG/awesomeTome#15]
The new feats file references file and folder structure that causes it not to compile. feats.orig compiles fine. Do you intend on importing the new structure to the legacysource folder, or was this unintentional?

**Comment by Lokathor** [comment]
I think the idea with "legacysource" it that we literally do not touch it at all ever again, and all future edits will be done within a different directory as we put things together, including copying sections from the legacy into the current version.

Note that many things in the AwesomeTome have not actually been released under OGL by the authors, and so we can't even use them yet. The AwesomeTome was put out under the Creative Commons license. That's partly illegal, but that's what they did.

Anyway, our stuff needs to be under the OGL, so we actually shouldn't be touching anything from Legacy at all until we have confirmed it as an OGL contribution. So the only "Tome" material that we should be including so far is the actual Frank and K material (which they put out under the public domain).

**Comment by ExplosiveRunes** [comment]
That's what I thought, I think the change was unintentional, but as it is it is not compileable.

On the note of OGL, I personally wrote/formatted the basics, character creation, and conditions and special abilities chapters in total. I also am the sole author of the combat and combat2 files. Of those things, probably only the combat and combat2 files (and maybe the conditions and special abilities chapter?) will move on to the new pdf. So those are a go for OGL.

**Comment by Lokathor** [comment]
Cool, cool. I stuck an "outline only" PDF into the repo just now. I think that if we can agree on a chapter and section outline, or at least a starting outline, then we can begin moving legacy tome stuff and SRD stuff to a "current" version of the product, and then expanding and writing and so forth.

**Comment by SqueeG** [comment]
That's a left-over file from when I was testing my changes last night. I'll get rid of it.

**Comment by SqueeG** [comment]
Fixed it, all should be well. Closing the topic.
