### ISSUE TITLE
Contribution and Credits

### ISSUE THREAD

**Issue by Lokathor** [SqueeG/awesomeTome#30]
Did we ever get a topic going on TGD about asking folks if they wanted to officially contribute their works into the compilation PDF, and if so, for them to link to which works they'd be find with including and what special copyright entry they might want (if any).

If we haven't done that, we should do that thing.

**Comment by SqueeG** [comment]
Wow. I totally thought this was a commit.

No, I don't think an actual thread was made for that.
@Tarkisflux , @ExplosiveRunes

**Comment by Lokathor** [comment]
I have this issue set for notifications, but didn't seem to get a notification about your reply. The whole system is fucked.

Anyway, I guess we should do that then.

**Comment by Tarkisflux** [comment]
I actually saw this as an issue and did get notifications, I've just been busy. Anyway, yes, yes we should. Volunteering Lokathor? 

If you are... should also ask if they want to enforce any editing limits on their work. Like "don't touch my words!" or "edit what's needed for compliance / coherence with the rest of it" or "edit whatever as long as the basic idea remains". And it probably need a disclaimer that officially contributing does not guarantee inclusion in the final work, or even transcription for inclusion in a custom build.

If you are not - I'll get to it in the next 72 hours or so. Probably.

**Comment by Tarkisflux** [comment]
In other news, we have class, feat, and monster templates people can use to format their own <del>shit</del> stuff. I could get a spell template up in a couple of days.

**Comment by Lokathor** [comment]
I suppose I could post a topic about it.

Here's the thing, and we should be clear with them on this, once they contribute it as Open Game Content for us to include in the PDF, they actually do lose all ability to tell us or anyone else to not edit it. _We_ might choose to respect a directive like "add it but don't change it", but others don't need to respect it at all. Open Game Content is free to be edited by anyone down the line as long as they just include the citation in their copyright section in their resultant work.

**Comment by SqueeG** [comment]
Still not quite understanding why we can't just use one of those various standard licenses to "protect" the authors' rights.

Just do a blanket catch all. Either they release it under the ever-so-slightly protective license, or they don't. I suppose, preferably, a license that allows for not-for-profit reproduction and required attribution.

**Comment by Lokathor** [comment]
Basically the answer is "Because that's how the OGL works".

Technically speaking, If we really wanted we could accept their OGL "work" where 100% of the work was declared to be product identity, and then dual license their product identity under another license, and then declare that stuff product identity in our own thing and then not release _our_ product identity under any license.

On another note though, if they're not willing to have their stuff be open content that anyone can use and modify however they want (or almost however they want) then what's the point of preserving their effort into the future? If they don't wanna add back into the collective, they should probably go do that some other place.

**Comment by SqueeG** [comment]
> On another note though, if they're not willing to have their stuff be open content that anyone can use and modify however they want (or almost however they want) then what's the point of preserving their effort into the future? If they don't wanna add back into the collective, they should probably go do that some other place.

Yea, I get that... the internet is full of such jerky trolls, though. It's more a thought of "I hate when people pawn off someone else's work as their own" kinda thing. We've been down this road before, I was just hoping we could collectively "protect" (however futile) the work against "malicious" intent/use/etc. Especially if it's only as much effort as adding in a clause at the beginning/end.

**Comment by Lokathor** [comment]
I mean if someone is gonna violate a single license system they're probably gonna violate a dual-license system too. This is all on GitHub and if someone wants they could just copy it all down, strip the credits, and then stick it out there under their own name.

The OGL enforces that (if they're following the license terms) they have to keep in all the Copyright lines from any work they base their own work off of. All of them. The credits sections just keep getting huger and huger over time if too many people keep using from other people. Even if you just use a small portion of someone else's thing, you have to include all of their copyright credits. In that way, people get credit for their work, even if their work gets heavily modified or even removed in later versions.

**Comment by Tarkisflux** [comment]
Protecting against malicious intent is almost certainly a waste of our time, as enforcement of that would fall onto us anyway. And since I'm not going to patrol sites to find and then hire lawyers to fight it, I sort of don't care. Whether or not we can dual license parts of it through declaring product identity  or without it seems pretty moot if we're not going to get an army of lawyers to enforce it. We need a license that allows for copying and distribution, and though I would prefer one of the CC licenses enough of the work is already OGL that we might as well just use the whole thing.

So, as project overlord I decree that we will use the <del>somewhat bullshit</del> OGL license for the entire work. If people contribute material, they get to determine how / if they are credited. They also get to make requests as to how intact we leave their work. We don't need <i>that</i> much additional content to pad out the core work, and so I'd rather know up front if making making changes to someone's special snowflake would offend them.

**Comment by Lokathor** [comment]
I did happen to ask Koumei already (since I wanted to put Dragonfire Adept in a thing) and they said that they'd love for their stuff to be used, and a generic credit line like

> Koumei's Compiled Tome Stuff Copyright 2006-2014, Koumei 

would be fine. Others will probably feel similar I expect. Also, the tomes themselves obviously are available. This leaves just needing to get a whole pile of small things from lots of people. A feat here and there, a race here and there, some PrCs, some base classes, etc.

**Comment by Lokathor** [comment]
## Alright, well, Here's a post that I'll throw up on TGD sometime soon if there's no objections:

So we're working on the next iteration of the Awesome Tome, the "tome stuff compilation PDF" thing.

You can find it here: https://github.com/SqueeG/awesomeTome

(We don't have any new releases yet, so right now our "releases" section is just the older PDF versions.)

Anyway, this is where you all come in! The old AwesomeTome didn't actually get contribution credits for a whole lot of the things that it included. We're trying to not go that route, so we want as many of you as possible that have written Tome things to give us the go-ahead to include your stuff in the PDF compilation. When we put in your thing you'll get a credit in our OGL copyright section and everything.

Right now all we've actually got in terms of proper crediting and author permission is this tiny list:

[b]Open Game License[/b] v 1.0a Copyright 2000, Wizards of the Coast, Inc.
[b]System Reference Document[/b] Copyright 2000-2003, Wizards of the Coast, Inc.; Authors Jonathan Tweet, Monte Cook, Skip Williams, Rich Baker, Andy Collins, David Noonan, Rich Redman, Bruce R. Cordell, John D. Rateliff, Thomas Reid, James Wyatt, based on original material by E. Gary Gygax and Dave Arneson.
[b]Tome of Necromancy[/b] Copyright 2006, Frank Trollman and K
[b]Tome of Fiends[/b] Copyright 2006, Frank Trollman and K
[b]Dungeonomicon[/b] Copyright 2006, Frank Trollman and K
[b]Races of War[/b] Copyright 2006, Frank Trollman and K
[b]Book of Gears[/b] Copyright 2007, Frank Trollman and K
[b]Koumei's Compiled Tome Stuff[/b] Copyright 2006-2014, Koumei

So clearly we need more content. If you want your stuff included just post one or more links to what we can include and if you want us to credit you under a real name or your username or what.

[i][b]Please Be Aware:[/b][/i] Once you have a thing included it becomes Open Game Content, which means that other people could pick up and edit your stuff and include it in their own OGL work as well (they'd have to carry over the credit though, just like we have the SRD credit in our PDF). The AwesomeTome project might even edit your things to make them fit in with the rest of the PDF (probably just formatting, but if we for example rewrite the Leadership rules then any class that gives a Leadership feat or Cohort might need a change).

If you're wildly averse to the idea of people potentially editing your works, then please don't have us include it.

**Comment by SqueeG** [comment]
Looks good. :)
Just noticed one spelling mistake.

> This is where you **_call**_ come in

**Comment by Lokathor** [comment]
oh damn, it's that thing where a typo makes another word so it doesn't even highlight.

**Comment by Tarkisflux** [comment]
Out for a couple of days, but that looks fine. And like it's gotten a decent reception on the Den. So yay that.

Any chance that you could change the [AwesomeTome] tag to [TRD] though? Branding and whatnot.

**Comment by Lokathor** [comment]
Suppose, though we might want to change the github project name as well if we're that concerned about it.

**Comment by Tarkisflux** [comment]
It's just what I've been using for threads on the den since people seemed to like it in the "What's in a name" issue. I'd rather keep using it until something we like more comes along, rather than revert to an older name.

And can we change the name of the github project? Is that a thing?

**Comment by Lokathor** [comment]
Looks like the project creator can in the Settings menu.
