### ISSUE TITLE
How does that class template even work?

### ISSUE THREAD

**Issue by Lokathor** [SqueeG/awesomeTome#31]
I had a "tome compilation" thing of my own, and so when i tried to add the class template stuff to my classes using the \goodfor and \goodbab commands and so on, it showed the table just fine, but then none of the \ifx statements computed properly, and so it always shows low BAB and poor saves.

Does whoever made the class template have any idea of what's going on? Or what I might have forgotten to import or something?

**Comment by SqueeG** [comment]
I found this on the [Tex SO](http://tex.stackexchange.com/questions/31652/what-is-the-difference-between-ifx-somecommand-undefined-and-ifdefined-somecom/31656#31656) ... it explains what \ifx does.

Do you want to post your current file as a [gist](https://gist.github.com)? Or did you just copypasta a whole file?

Which TeX setup are you using now?

@Tarkisflux , @ExplosiveRunes

**Comment by Lokathor** [comment]
Well I've got all my commands in here
https://github.com/Lokathor/SuperTome/blob/master/commands.tex

I copped them from the awesomeTome version exactly.

An example entry with the Fighter or Warrior:
https://github.com/Lokathor/SuperTome/blob/master/classes-pc/fighter.tex
https://github.com/Lokathor/SuperTome/blob/master/classes-npc/warrior.tex

And then the output is to always show the low save rate and wizard bab rate, no matter what the rates you set are.
https://github.com/Lokathor/SuperTome/blob/master/SuperTome.pdf

The confusing part is that MikTex can compile the awesomeTome properly, and it makes the tables show up correctly. So it seems like there's some bit of configuration that I forgot or did wrong or something.

**Comment by Tarkisflux** [comment]
Fucking Tark's thing. How does it work?

I have no idea. Really. I'd have to go back and relearn it all, because if
functionality in LaTeX is alien and bizarre. But a search of \empty shows
that you're missing a couple of comparison commands, and the comments on
them indicate that they're needed for comparison stuff. You should probably
include them, and maybe things will work?

Here you go:
\newcommand{\testempty}{\empty}
\newcommand{\isempty}{\empty}
%Two commands that can be compared to one another for \ifx logic tests.
\isempty should never be changed. If \testempty holds a value of anything
but empty, the test should return false.

**Comment by Tarkisflux** [comment]
Double email post!

Yeah, you're missing the \isempty definition, so the comparisons are all
failing. Adding that one should cover you... I think. Not sure if you'll
still need the \testempty or not.

**Comment by SqueeG** [comment]
Where is `\isempty` defined?

edit: Never mind  ... `tome-ref-doc.tex` ... derp.

**Comment by Lokathor** [comment]
Okay, did that, now it works.

Strange that it'll happily test \isempty even when it doesn't exist, when elsewhere a missing command will cause a compile time failure.

**Comment by Tarkisflux** [comment]
It's defined in the tome-ref-doc.tex file, in the logic section.

**Comment by SqueeG** [comment]
I forgot you're keeping tabs through email. 
I already edited my original post to say I found it. I also slapped myself in the forehead, but that was unreported.
