### ISSUE TITLE
Left Floats For Spell Data

### ISSUE THREAD

**Issue by Tarkisflux** [SqueeG/awesomeTome#32]
I've been toying with a spell template that works in a 1-column format, but I'm having problems with getting the spell data set nicely. There's a floating figure in the assassin class that sits on the right and text flows around it on the left, but I can't get a float on the left with text around it on the right. And since I'm not having look on my own and I'm tired, I thought it time to ask for assistance.

So @Lokathor, @ExplosiveRunes, @SqueeG... anyone got anything?

**Comment by Lokathor** [comment]
wraptable and wrapfig let you have the item on the left or right, and text flows around it.

a minimal example from my After Sundown PDF goes like this

\begin{wrapfigure}[16]{L}{4.5cm} \vspace{-.25cm}
\includegraphics[width=4.5cm]{timlewisnm_farkle-jar.jpg}
\end{wrapfigure}

**Comment by Tarkisflux** [comment]
I can't get the text to sit on the left without falling out into the margin and off the page, and when it's on the right it gets jumbled up with other text. Not sure where the fuck up is, but I've committed it in case anyone else wants to take a look at it and give me a hand.

**Comment by Lokathor** [comment]
I have a fix, but you probably wont' like it. It seems that you can't stick a wraptable inside of another environment and have it work, for whatever reason. Probably because another library is hooking into the formatting process and looking for "wraptable" to be the active environment not "spelltable" or whatever. That's the only reason I can think of.

**Comment by Tarkisflux** [comment]
It works if you put it in a newcommand instead of a new environment though (see commit), which is good enough for me. Thanks a lot for helping sort that.

Now I just need to figure out how to get text to clear a float, so that a new spell never starts in the trailing whitespace of a previous one and screw up the formatting (like the second copy of acid fog does right now). Know anything about clearing a float, or does that need to happen manually?

**Comment by Lokathor** [comment]
The only thing I know that does that is \clearpage{}, which isn't really what you'd want at all.

**Comment by Tarkisflux** [comment]
Will screw with it more tomorrow then. Thanks again.
