### ISSUE TITLE
Include the Book of Elements?

### ISSUE THREAD

**Issue by saulrh** [SqueeG/awesomeTome#7]
Do we want to include chunks of IGTN's [Book of Elements](http://dnd-wiki.org/wiki/Book_of_Elements_%283.5e_Sourcebook%29)? I've played with it before and think it's on par with the other Tomes quality-wise, and the style and content fit. Including it would be pretty low-overhead since the vast majority of it is classes, feats, spheres, and writeups. The real question is whether we consider the BoE to be a "Tome", and I don't know what the community opinion there is.

**Comment by Lokathor** [comment]
I'm for anything that includes more "High Adventure in ___" sections. We'd need to get the creators to agree to have it under the OGL, but other than that we should include it.

**Comment by Tarkisflux** [comment]
IGTN would probably be ok with including it, but I don't want his high powerful races in there without racial hit dice adjustments instead of the current minimum level nonsense (which better fits with RoW monsters anyway).

And I second an increase in the "high adventure in X" sections.

**Comment by SqueeG** [comment]
At first that LOOKED like a lot to add. But most of what I've read so far is theory and design reasoning. Which could be split out to "Ravings of Madmen".

**Comment by Tarkisflux** [comment]
I think dropping the ravings as separate and incorporating them into the Mister Cavern Handbook (or Guide) is probably a better way to go. Most of those things are advice on building dungeons or adventures or campaigns or whatever anyway, and that's perfect fodder for that sort of book.

**Comment by Tarkisflux** [comment]
So this seems rather quiet now. Going to call it closed with the following resolution:

Subject to permission - some feats and spells potentially incorporated into PHB. The remainder + classes + races moved into community classplosion appendices. Adventuring sections considered for inclusion in MCG when we get to that phase.
